/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-08-12 22:10:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminPageExample_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Home Page</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <style>\r\n");
      out.write("  .fakeimg {\r\n");
      out.write("    height: 200px;\r\n");
      out.write("    background: #aaa;\r\n");
      out.write("  }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"jumbotron text-center\" style=\"margin-bottom:0\">\r\n");
      out.write("  <h1>Bernice's International Preparatory School</h1>\r\n");
      out.write("  <p>Where Wisdom is Acquired through Application of Knowledge!</p> \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-sm bg-dark navbar-dark\">\r\n");
      out.write("  <a class=\"navbar-brand\" href=\"#\"><h1 style=\"font-size: 50px; font-weight: bold;\"><span style=\"color:blue; font-size:;\">BI</span>PS </h1></a>\r\n");
      out.write("  <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#collapsibleNavbar\">\r\n");
      out.write("    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("  </button>\r\n");
      out.write("  <div class=\"collapse navbar-collapse\" id=\"collapsibleNavbar\">\r\n");
      out.write("    <ul class=\"navbar-nav\">\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/general/homePage\">Home</a>\r\n");
      out.write("      </li> \r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/schoolStudents/moreStudentsForm\">Enroll Student</a>\r\n");
      out.write("      </li> \r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/schoolParents/showParentForm\">Add Parent</a>\r\n");
      out.write("      </li> \r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/schoolStudents/displayStudents\">Display Student</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/schoolParents/displayParents\">Display Parent</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/schoolStudents/showStudentsForm\">Add Teacher</a>\r\n");
      out.write("      </li> \r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/studentAddress/displayStudentAddress\">Add Student Address</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/schoolTeachers/displayTeachers\">All Teachers</a>\r\n");
      out.write("      </li>  \r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/general/lowerResults\">Get Results</a>\r\n");
      out.write("      </li>      \r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>  \r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\" style=\"margin-top:30px\">\r\n");
      out.write("  <div class=\"row\">\r\n");
      out.write("    <div class=\"col-sm-4\">\r\n");
      out.write("      <h2>Administrator</h2>\r\n");
      out.write("      <h5>Photo of me:</h5>\r\n");
      out.write("      <div class=\"fakeimg\"> <img alt=\"our mision\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/png/mission.png\" style=\"width:100%; height:100%;\"/>  </div>\r\n");
      out.write("      <p>Administrator of BIPS..</p>\r\n");
      out.write("      \r\n");
      out.write("    <!--   academic record start here -->\r\n");
      out.write("    \r\n");
      out.write("      <h3>Academic Records</h3>\r\n");
      out.write("      <p>Enter Examination records here.</p>\r\n");
      out.write("      <ul class=\"nav nav-pills flex-column\">\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link active\" href=\"#\">results entry</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"#\">Year One</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"#\">Year Two</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"#\">Year Three</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link disabled\" href=\"#\">Disabled</a>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      <hr class=\"d-sm-none\">\r\n");
      out.write("      \r\n");
      out.write("      <!-- academic record ends here -->\r\n");
      out.write("      \r\n");
      out.write("      <!-- student starts here -->\r\n");
      out.write("       <h3 style=\"background-color:gold;\">Students enrollment</h3>\r\n");
      out.write("      <p>students here.</p>\r\n");
      out.write("      <ul class=\"nav nav-pills flex-column\">\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link active\">Enrollment</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"#\">Year One</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"#\">Year Two</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"#\">Year Three</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <!-- <a class=\"nav-link disabled\" href=\"#\">Disabled</a> -->\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-info float-left\" data-toggle=\"modal\" data-target=\"#myModal\">Add Student</button>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      <hr class=\"d-sm-none\">\r\n");
      out.write("    <!--   students ends here -->\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- mission start here -->\r\n");
      out.write("    <div class=\"col-sm-8\">\r\n");
      out.write("      <h2>OUR VISION</h2>\r\n");
      out.write("      <h5>Title description, Dec 7, 2017</h5>\r\n");
      out.write("      <div class=\"fakeimg\">  Our vision is to develop well rounded, confident and responsible individuals who aspire to achieve their full potential. We will do this by providing a welcoming, happy, safe, and supportive learning environment in which everyone is equal and all achievements are celebrated. </div>\r\n");
      out.write("      <p>Some text..</p>\r\n");
      out.write("      <p>Our vision is to develop well rounded, confident and responsible individuals who aspire to achieve their full potential. We will do this by providing a welcoming, happy, safe, and supportive learning environment in which everyone is equal and all achievements are celebrated. </p>\r\n");
      out.write("      \r\n");
      out.write("      <!-- mission end here -->\r\n");
      out.write("      \r\n");
      out.write("      <br>\r\n");
      out.write("      <h2>OUR MISSION</h2>\r\n");
      out.write("      <h5>Title description, Sep 2, 2017</h5>\r\n");
      out.write("      <div class=\"fakeimg\"><img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/png/mission.png\" style=\"width:100%; height:100%;\"></div>\r\n");
      out.write("      <p>Some text..</p>\r\n");
      out.write("      <p>We are dedicated to a continuing tradition of excellence in an ever-changing world. Within a safe and supportive environment, we provide a relevant, high-quality education and prepare our diverse student body for future endeavors. We honor achievement and promote pride in ourselves, in our school, and in our community.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"jumbotron text-center\" style=\"margin-bottom:0; align-context: space-between;\">\r\n");
      out.write("<div style=\"justify-content: center;\">\r\n");
      out.write("<div style=\"display: flex; float: center; justify-content: center;\"> \r\n");
      out.write("<p style=\"margin-right: 10em\">address: <br /> Post Office Box SQ 90 Tema</p> <p style=\"border-left: 1px solid black; height: 80px; position:fix; left: 35%; padding-right: 2em;\"> </p>\r\n");
      out.write("<p style=\"display: flex; float: right;\"> Location: <br /> Behind Baatsona Fuel Station, <br> Baatsona, Lashiba </p> <P style=\"border-left: 1px solid black; height: 80px; position:fix; right: 50%; margin-left: 6em;\"> </P>\r\n");
      out.write("<p style=\"margin-left: 10em\">contact us:<br/> 0207173313</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- test form -->\r\n");
      out.write("\r\n");
      out.write(" <div class=\"container\">\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-info float-left\" data-toggle=\"modal\" data-target=\"#myModal\">Add Student</button>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Modal -->\r\n");
      out.write("\t\t<div class=\"modal fade\" id=\"myModal\" role=\"dialog\">\r\n");
      out.write("\t\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Modal content-->\r\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"modal-title text-primary\">ADD NEW STUDENT</h4>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/aitiKaceStudentsApiConsumption/saveAitiKaceStudent=SaMEmE=HsuSGS-MlsjHS-DN-aDDF-Fdddde-sAmKoG=SmO-sLnINbds=LonCrshs-bBidbdd\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("   \t\t\t\t\t\t\t <div class=\"col\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input name=\"student_id\" type=\"text\" class=\"form-control checking_student_id\" id=\"student_id\" value=\"\" placeholder=\"Student ID\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"error_student_id\" id=\"student_id_error_message\" style=\"color:red;\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col\">\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t <input name=\"student_name\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"text\" class=\"form-control\" id=\"student_name\" value=\"\" placeholder=\"Student Name\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span id =\"student_name_error_message\" style=\"color:red;\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label>COURSE</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select class=\"form-control\" name=\"course\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"\">Select Course</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Certificate in Software Development\">Certificate in Software Development</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Cisco Certified Network Associate\">Cisco Certified Network Associate</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Cisco Certified Network Professionals\">Cisco Certified Network Professionals</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"International Computer Driving Licence\">International Computer Driving Licence</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Cyber Security\">Cyber Security</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Network Information Security\">Network Information Security</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Certified Information System Auditor\">Certified Information System Auditor</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Big Data Analytics\">Big Data Analytics</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Web Technologies\">Web Technologies</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Java Programming\">Java Programming</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Computing Infrastructure Systems & Security\">Computing Infrastructure Systems & Security</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("    <div class=\"col\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>COURSE LEVEL</label> <input name=\"course_level\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"text\" class=\"form-control\" id=\"course_level\" value=\"\" placeholder=\"CSD1.5\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span id =\"course_level_error_message\" style=\"color:red;\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("   <div class=\"col\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label>DATE OF BIRTH</label> <input name=\"date_of_birth\" type=\"date\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"form-control checking_date_of_birth\" id=\"date_of_birth\" value=\"\" placeholder=\"example@play.com\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"error_date_of_birth\" id=\"date_of_birth_error_message\" style=\"color:red;\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>EMAIL</label> <input name=\"email\" type=\"email\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"form-control checking_email\" id=\"email\" value=\"\" placeholder=\"example@play.com\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"error_email\" id =\"email_error_message\" style=\"color:red;\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("    <div class=\"col\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>PHONE NUMBER</label>\t<input name=\"phone\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"form-control checking_phone\" id=\"phone\" value=\"\" placeholder=\"0*************\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"error_phone\" id =\"phone_error_message\" style=\"color:red;\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\t\t\t\t\t\r\n");
      out.write(" <div class=\"col\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label>GENDER</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select class=\"form-control\" name=\"gender\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>Select</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Male\">Male</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Female\">Female</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label>ADDRESS</label> <input name=\"address\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"text\" class=\"form-control\" id=\"address\" value=\"\" placeholder=\"Tema Comm 1\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span id =\"course_level_error_message\" style=\"color:red;\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("    <div class=\"col\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label>COURSE START DATE</label> <input name=\"course_start_date\" type=\"date\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"form-control checking_date_of_birth\" id=\"course_start_date\" value=\"\" placeholder=\"example@play.com\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"error_date_of_birth\" id=\"date_of_birth_error_message\" style=\"color:red;\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("  <div class=\"col\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label>COURSE END DATE</label> <input name=\"course_end_date\" type=\"date\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"form-control checking_date_of_birth\" id=\"course_end_date\" value=\"\" placeholder=\"example@play.com\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"error_date_of_birth\" id=\"date_of_birth_error_message\" style=\"color:red;\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
