/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-07-03 20:39:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class homeExample_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("a:link{\r\n");
      out.write("color: red;\r\n");
      out.write("}\r\n");
      out.write("a:visited{\r\n");
      out.write("color: green;\r\n");
      out.write("}\r\n");
      out.write("li:hover{\r\n");
      out.write("background-color: green;\r\n");
      out.write("transition: 5s;\r\n");
      out.write("color: red;\r\n");
      out.write("}\r\n");
      out.write(".article{\r\n");
      out.write("padding: 2em;\r\n");
      out.write("color: white;\r\n");
      out.write("animation: mymove 5s infinite;\r\n");
      out.write("position: relative;\r\n");
      out.write("}\r\n");
      out.write("@keyframes mymove{\r\n");
      out.write("from{background-color: red;\r\n");
      out.write("}\r\n");
      out.write("to{background-color: blue;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("h3:before{\r\n");
      out.write("content: '\\260E';}\r\n");
      out.write("\r\n");
      out.write(".aside{\r\n");
      out.write("padding: 2em;\r\n");
      out.write("color: white;\r\n");
      out.write("position: relative;\r\n");
      out.write("animation-name: myaside;\r\n");
      out.write("animation: myaside 6s infinite;\r\n");
      out.write("}\r\n");
      out.write("@keyframes myaside{\r\n");
      out.write("from{background-color: green;}\r\n");
      out.write("to {background-color: rgb(145,74,152);}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/index.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write(" <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("<title>ADMIN HOME</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color:gold;\">\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg bg-dark navbar-dark\">\r\n");
      out.write("  <a class=\"navbar-brand\" href=\"#\"><h1 style=\"font-size: 50px; font-weight: bold;\"><span style=\"color:blue; font-size:;\">BI</span>PS </h1></a>\r\n");
      out.write("  <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#collapsibleNavbar\">\r\n");
      out.write("    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("  </button>\r\n");
      out.write("  <div class=\"collapse navbar-collapse\" id=\"collapsibleNavbar\" style=\"color:black;\">\r\n");
      out.write("    <ul class=\"navbar-nav\" style=\"background-color:; \">\r\n");
      out.write("      <li class=\"nav-item\" style=\"background-color:blue;\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/general/logIn\">Home</a>\r\n");
      out.write("      </li> \r\n");
      out.write("      <li class=\"nav-item\" style=\"background-color:blue;\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/general/teacherLogin\">enrol student</a>\r\n");
      out.write("      </li> \r\n");
      out.write("      <li class=\"nav-item\" style=\"background-color:blue;\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/general/parentLogin\">add parent</a>\r\n");
      out.write("      </li> \r\n");
      out.write("      <li class=\"nav-item\" style=\"background-color:blue;\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/schoolStudents/studentsForm\">Display student</a>\r\n");
      out.write("      </li> \r\n");
      out.write("      <li class=\"nav-item\" style=\"background-color:blue;\"><a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/studentAddress/displayStudentAddress\">Student Address</a></li>\r\n");
      out.write("      <li class=\"nav-item\" style=\"background-color:blue;\"><a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/schoolStudents/showStudentsForm\">Add Teacher</a></li>\r\n");
      out.write("      <li class=\"nav-item\" style=\"background-color:blue;\"><a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/schoolTeachers/displayTeachers\">All Teachers</a></li>\r\n");
      out.write("      <li class=\"nav-item\" style=\"background-color:blue;\"><a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/general/lowerResults\">getLowerResults</a></li>\r\n");
      out.write("               \r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>  \r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write(" <div id='firstHeader' class='firstHeader' name='firstHeader'>\r\n");
      out.write("        \r\n");
      out.write("        <h1 style=\"text-align:center\"><ins>Bernice's International Preparatory School <p>(<abbr title=\"Bernice's International Preparatory School\">BIPS</abbr>)</p></ins></h1>\r\n");
      out.write("    </div>\r\n");
      out.write("    <nav style=\"align-content:center; justify:center;\" class=\"navbar navbar-expand-lg bg-dark navbar-dark\">\r\n");
      out.write("   <div style=\"display: flex;\">\r\n");
      out.write("    <div> <ul> <li> <h1 style=\"color:gold; font-weight: 900;\"><span style=\"color:blue;\">BI</span>PS</h1> </li> </ul></div>\r\n");
      out.write("     <div>\r\n");
      out.write("     <button style=\"position: relative; right:-35em; top:2em;\" class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#collapsibleNav\">\r\n");
      out.write("    <span  class=\"navbar-toggler-icon\" ></span>\r\n");
      out.write("  </button>\r\n");
      out.write("     \r\n");
      out.write("     <div class=\"collapse navbar-collapse\" id=\"collapsibleNav\">\r\n");
      out.write("     <ul style=\"align-content:center; justify:center; display:inline-block;\">\r\n");
      out.write("            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/general/homePage\">HOME</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/schoolStudents/moreStudentsForm\">Enroll Student</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/schoolParents/showParentForm\">Add Parent</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/schoolStudents/displayStudents\">Display Student</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/schoolParents/displayParents\">Display Parent</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/studentAddress/displayStudentAddress\">Student Address</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/schoolStudents/showStudentsForm\">Add Teacher</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/schoolTeachers/displayTeachers\">All Teachers</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/general/lowerResults\">getLowerResults</a></li>\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("          <li>  \r\n");
      out.write("  <div class=\"dropdown\" style=\"background-color:blue;\">\r\n");
      out.write("  <button type=\"button\" class=\"btn btn-primary dropdown-toggle\" data-toggle=\"dropdown\" >\r\n");
      out.write("    Add Results\r\n");
      out.write("  </button>\r\n");
      out.write("  <div class=\"dropdown-menu\">\r\n");
      out.write("    <a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lowerPrimary/saveResults\">Primary One</a>\r\n");
      out.write("    <a class=\"dropdown-item\" href=\"#\">Primary Two</a>\r\n");
      out.write("    <a class=\"dropdown-item\" href=\"#\">Primary Three</a>\r\n");
      out.write("    <a class=\"dropdown-item\" href=\"#\">Primary Four</a>\r\n");
      out.write("    <a class=\"dropdown-item\" href=\"#\">Primary Five</a>\r\n");
      out.write("    <a class=\"dropdown-item\" href=\"#\">Primary Six</a>\r\n");
      out.write("    <a class=\"dropdown-item\" href=\"#\">JHS One</a>\r\n");
      out.write("    <a class=\"dropdown-item\" href=\"#\">JHS Two</a>\r\n");
      out.write("    <a class=\"dropdown-item\" href=\"#\">JHS Three</a>\r\n");
      out.write("  </div>\r\n");
      out.write("</div></li> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     <li style=\"background-color: blue;\"> <form class=\"form-inline\" action=\"searchIdOrName.jsp\">\r\n");
      out.write("    \t\t\t<input class=\"form-control mr-sm-2\" type=\"text\" name= \"search\" placeholder=\"Search\" style=\"margin-top: 0.7em; height: 2.6em; border-radius: 0.8em;\">\r\n");
      out.write("    \t\t\t<button class=\"btn btn-success\" type=\"submit\" style=\"height: 2.8em; padding: 0.5em; margin-top:0.5em; width:10em; border-radius:0.8em;\">Search</button>\r\n");
      out.write("  \t\t\t</form>\r\n");
      out.write("      \r\n");
      out.write("          </li>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("        <!-- <ul > <li style=\"background-color: blue;\"> </li> <li style=\"background-color: blue;\"> </li> </ul> -->\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("</div>   \r\n");
      out.write("</div>   \r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("<br/>\r\n");
      out.write("<br />\r\n");
      out.write("<h1 style='text-align: center;'>Welcome to Bernice's Preparatory School Website</h1>\r\n");
      out.write("<br/> <br/>\r\n");
      out.write(" <p style=\"text-align:center\"> <h2 style=\"text-align:center\" > Welcome to Admin Home </h2></p> <br /> <br />\r\n");
      out.write(" \r\n");
      out.write(" <section style=\"display:flex-center; width:100%; text-align:center;\">\r\n");
      out.write(" <article class=\"article\" style=\"display:;display:inline-block; width:40%; border: 2px solid green; background-color:red;\">\r\n");
      out.write("  <header style=\"display:center;\"> <h1 style=\"text-align:center;\"> <ins> Our Vision</ins></h1> <br/>\r\n");
      out.write("   <p><h2>Our vision is to develop well rounded, confident and responsible individuals who aspire to achieve their full potential. We will do this by providing a welcoming, happy, safe, and supportive learning environment in which everyone is equal and all achievements are celebrated. </h2></p>\r\n");
      out.write("</header>\r\n");
      out.write("</article><br /> <br /><br /> <br /><br /> <br /><br /> <br />\r\n");
      out.write("<aside class=\"aside\" style=\"display:inline-block; width:40%; background-color:green;  height: 50%;\" >\r\n");
      out.write("<article >\r\n");
      out.write("\r\n");
      out.write("<header> <h2> <ins> Our Mission</ins></h2></header>\r\n");
      out.write("<h2> <p> We are dedicated to a continuing tradition of excellence in an ever-changing world. Within a safe and supportive environment, we provide a relevant, high-quality education and prepare our diverse student body for future endeavors. We honor achievement and promote pride in ourselves, in our school, and in our community. </p></h2>\r\n");
      out.write("</article>\r\n");
      out.write("</aside>\r\n");
      out.write("</section>\r\n");
      out.write("<br /> <br/> <br/>\r\n");
      out.write("<aside id=\"mainFooter\" style=\"background-color:red;\">\r\n");
      out.write("<footer id=\"mainFooter\"  style=\"text-align:center; align-content:center;\">\r\n");
      out.write("<h3 style=\"display:bottom; \">Contact Us: 0207173313</h3>\r\n");
      out.write("\r\n");
      out.write("</footer>\r\n");
      out.write("</aside>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
